Django/users/apps/blogs/urls.py
from django.conf.urls import url
from apps.blogs import views

urlpatterns = [
    url(r'^$', views.index),
]

Django/users/apps/user_login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="my_index"),
    url(r'^new/$', views.new, name="my_new"),
    url(r'^(?P<id>\d+)/$', views.show, name="my_show"),
    url(r'^(?P<id>\d+)/edit/$', views.edit, name="my_edit"),
    url(r'^create/$', views.create, name="my_create"),
    url(r'^(?P<id>\d+)/destroy/$', views.destroy, name="my_delete"),
    url(r'^update/$', views.update, name="my_update"),
]

Django/users/users/urls.py
from django.conf.urls import url, include

# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.user_login.urls', namespace='users')),
]

Django/users/apps/user_login/models.py
from django.core.validators import MinLengthValidator, EmailValidator, MaxValueValidator, MinValueValidator
from django.db import models


# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=255, validators=[MinLengthValidator(2)])
    last_name = models.CharField(max_length=255, validators=[MinLengthValidator(2)])
    email_address = models.EmailField(max_length=255, unique=True, validators=[EmailValidator()])
    age = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(125)], null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # this isn't working... needed to restart shell and import again! (from apps.user_login.models import *)
    # def __repr__(self):
    #     return "<Users object: {} {} {} {}>".format(self.first_name, self.last_name, self.email_address, self.age)

    def __str__(self):
        return f"{self.first_name}"


class UserManager(models.Manager):
    def basic_validation(self, post_data):
        errors = {}
        if len(post_data['name_f'] < 3):
            errors['name_f'] = "Name must be at least 2 characters."
        return errors

Django/users/apps/user_login/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.contrib import messages
from apps.user_login.models import *


# Create your views here.
def index(request):
    # Retrieve all users from database
    users = User.objects.values().all()
    return render(request, "user_login/index.html", {'users': users})


def new(request):
    return render(request, "user_login/new_user.html")


def edit(request):
    return render(request, "user_login/edit_user.html")


def show(request):
    return None


def create(request):
    if request.method == "POST":
        errors = User.objects.basic_validator(request.POST)
        return redirect(reverse("users:my_show"), errors)


def destroy(request):
    return None


def update(request):
    return None

Django/users/apps/user_login/templates/user_login/edit_user.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit User</title>
    {% load static %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald|Shadows+Into+Light" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/user_login/css/bootstrap4-daydream.css' %}">
</head>

<body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
</body>

</html>

Django/users/apps/user_login/templates/user_login/index-bootstrap-template.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Daydream - Bootstrap Theme</title>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald|Shadows+Into+Light" rel="stylesheet">
  <link rel="stylesheet" href="static/css/bootstrap4-daydream.css">

</head>

<body>


  <div class="jumbotron bg-primary text-center text-white mb-0 radius-0">
    <div class="container">

      <h1 class="display-3 text-white text-handwriting text-uppercase">Programmers never</h1>
      <h1 class="display-1 text-success text-uppercase title-margin-fix">Daydream</h1>

      <div>
        <a href="#!" class="btn btn-outline-light btn-lg m-2 btn-hover-text-primary">
          <span>A Button</span>
        </a>

        <a href="#!" class="btn btn-outline-light btn-hover-text-primary btn-lg m-2">
          <span>Another button</span>
        </a>
      </div>
    </div>
  </div>



  <div class="container py-5">
    <h1>Thanks</h1>

    <p>Thank you for downloading this theme. If you have trouble or find a bug, please open an
      issue on GitHub:<br>
      <a href="https://github.com/HackerThemes/theme-machine">https://github.com/HackerThemes/theme-machine</a></p>


  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</body>

</html>

Django/users/apps/user_login/templates/user_login/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Users Index</title>
    {% load static %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald|Shadows+Into+Light" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/user_login/css/bootstrap4-daydream.css' %}">
</head>

<body>
<div class="container">
    <div class="jumbotron bg-primary pt-1 pb-2">
        <h1 class="display-2 text-handwriting text-white text-center ">User Index</h1>
        {# TODO: display messages/errors? #}
        <table class="table table-hover table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Created At</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody class="bg-light">
            {% for user in users %}
                <tr>
                    <th scope="row">{{ user.id }}</th>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email_address }}</td>
                    <td>{{ user.created_at }}</td>
                    <td class="btn-group">
                        <a href="{{ user.id }}" class="btn btn-outline-primary">Show</a>
                        <a href="{{ user.id }}/edit" class="btn btn-outline-warning">Edit</a>
                        <a href="{{ user.id }}/destroy" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="container text-center ">
    <a href="{% url 'users:my_new' %}" class="btn btn-outline-success btn-lg font-weight-bold">Add a new user</a>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
</body>

</html>

Django/users/apps/user_login/templates/user_login/new_user.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add New User</title>
    {% load static %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald|Shadows+Into+Light" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/user_login/css/bootstrap4-daydream.css' %}">
</head>

<body>
<form action="/users" method="post">
    {% csrf_token %}
    <input type="text" name="fname_f">

    <input type="text" name="email_f">
    <input type="password" name="password_f">
    <input type="password" name="password_confirm_f">
    <input type="submit" name="submit_f">
</form>

<div class="container">
    <form>
        {% csrf_token %}
        <div class="form-group row">
            <label for="fname_f" class="col-sm-2 col-form-label">First Name:</label>
            <input type="text" class="form-control col-sm-10" name="fname_f" placeholder="First Name">
        </div>
        <div class="form-group row">
            <label for="fname_f" class="col-sm-2 col-form-label">Last Name:</label>
            <input type="text" class="form-control col-sm-10" name="fname_f" placeholder="Last Name">
        </div>
        <div class="form-group row">
            <div class="offset-sm-2 col-sm-10">
                <input type="submit" class="btn btn-primary shadow">Submit</input>
            </div>
        </div>
    </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
</body>

</html>

Django/users/apps/user_login/templates/user_login/show_user.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Show User</title>
    {% load static %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald|Shadows+Into+Light" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/user_login/css/bootstrap4-daydream.css' %}">
</head>

<body>
{% for user in users %}

{% endfor %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
</body>

</html>